[theme]
primaryColor = "#981D97"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F5F5"
textColor = "#54585A"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[runner]
fastReruns = true
